title: msuicc
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  This will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format, refer to Jekyll liquid filters for dates if you want to change this. 
minima:
  date_format: "%d %B %Y"
  skin: dark

collections: 
  projects:
    output: true
    permalink: /:collection/:title


# Link specific pages in header, add the path to the pages in order as they should show up
header_pages:
 - archive.md
 - projects.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
